feature/add-bd-connect
s21platform/friends-service pull request #12
Opened 2024-07-14 14:17 UTC by njohanne

2024-07-14 14:24 UTC, aleksakokorewa commented
conStr := fmt.Sprintf("user=%s password=%s dbname=%s host=%s port=%d sslmode=disable",
		"myuser", "mypassword", "mydatabase", "localhost", 5433)

вот эта штука некорректная, нужно переделать

2024-07-14 15:37 UTC, alexseipopov commented
@njohanne а где main.go? ты его либо забыл, либо там не подрубил БД. Там нужно вызвать New, проверить ошибку и после, чтобы не жаловался `_ = db` написать (или как ты там эту переменную назовешь) И кстати Саша помоему конфиг в _ заносила, тут созай имя,cfg например и пробрось в New()

2024-07-14 16:52 UTC, aleksakokorewa commented
вместе родили, меня устраивает)

2024-07-14 18:14 UTC, aleksakokorewa commented
Теперь вроде бы хорошо

2024-07-20 20:30 UTC, alexseipopov requested changes

2024-07-20 20:42 UTC, alexseipopov commented
@njohanne @aleksakokorewa fyi. Возможно вы знаете, но я напишу, не судите строго. В goland для переименования лучше использовать: для файлов: правой кнопкой на файле -> refactor -> rename; для переменных: правой кнопкой на переменную -> rename -> refactor (возможно там сразу будет, без подкатегории refactor). Goland индексирует проект и при таком подходе сам по всему проекту поменяет названия

2024-07-21 09:25 UTC, alexseipopov approved these changes

2024-07-21 09:45 UTC, merged