added consumer
s21platform/friends-service pull request #15
Opened 2024-07-22 16:35 UTC by aleksakokorewa

добавлен консьюмер для Кафка

2024-07-22 17:28 UTC, alexseipopov requested changes

2024-07-22 17:28 UTC, alexseipopov commented on cmd/workers/notification/main.go
> +	config2 "github.com/s21platform/friends-service/internal/config"
Вот тут видимо как-то скопировалось откуда-то, лучше это конфиг2 убрать и просто конфиг юзать далее

2024-07-22 17:28 UTC, alexseipopov commented on cmd/workers/notification/main.go
> +	cfgMap := &kafka.ConfigMap{
Эту логику лучше в нью унести, в Майне только нью методы вызываются и основная логика

2024-07-22 17:28 UTC, alexseipopov commented on cmd/workers/notification/main.go
> +	if err != nil {
Этот консьюмер можно уложить в структуру кафки в методе нью и иметь к ней доступ в мейне, чтобы дефером кенсельнуть. По аналогии с базой данных

2024-07-22 17:35 UTC, alexseipopov commented
@aleksakokorewa Кстати этот файл надо запускать в докерфайле, так же скомпилить и запускать во втором контейнере, вместе с основным main.go

2024-07-22 18:48 UTC, aleksakokorewa commented on cmd/workers/notification/main.go
> +	if err != nil {
я так и сделала же

2024-07-22 20:30 UTC, aleksakokorewa commented
@alexseipopov вроде сделала, но с докерфайлом какая то магия

2024-07-31 11:43 UTC, alexseipopov approved these changes

2024-07-31 11:43 UTC, merged