Feature/worked kafka
s21platform/friends-service pull request #58
Opened 2024-09-02 17:35 UTC by njohanne

2024-09-05 13:57 UTC, alexseipopov commented on internal/repository/Kafka/consumer/consumer.go
>  package consumer
consume_new_user

2024-09-05 14:00 UTC, alexseipopov commented on internal/repository/Kafka/consumer/consumer.go
> +func (kc *KafkaConsumer) Process() []byte {
возвращать ошибку

2024-09-05 14:00 UTC, alexseipopov commented on internal/repository/Kafka/producer/producer.go
неминг producer_notification_new_user

2024-09-05 14:02 UTC, alexseipopov commented on internal/repository/Kafka/consumer/consumer.go
> +		Topic:   cfg.Kafka.TopicForReading,
топик так же назвать семантически

2024-09-05 14:07 UTC, alexseipopov commented on internal/repository/db/repository.go
> +func (r *Repository) GetUUIDForEmail(email []byte) (string, error) {
возвращать слайс стрингов

2024-09-05 14:13 UTC, alexseipopov requested changes

2024-09-05 14:13 UTC, alexseipopov commented on internal/repository/Kafka/producer/producer.go
> +		return fmt.Errorf("json.Marsha: %v", err)
marsha**l**

2024-09-05 14:13 UTC, alexseipopov commented on cmd/workers/notification/main.go
> +	go func() {
реализуем через воркер

2024-09-06 11:52 UTC, alexseipopov requested changes

2024-09-06 11:52 UTC, alexseipopov commented on internal/repository/kafka/consumer/consumer_notification_new_user/consumer.go
> +func New(
Тут нужно принимать как интерфейсы. Их нужно прописать в контракте местном, чтобы потом тесты накатить можно было

2024-09-06 11:52 UTC, alexseipopov commented on internal/repository/kafka/producer/producer_notification_new_user/producer.go
>  	return kp.Producer.Close()
В kafka producer давай уберем Topic из структуры и так же будем принимать интерфейс

2024-09-06 15:02 UTC, dreamcoiI approved these changes

2024-09-06 15:04 UTC, dreamcoiI commented
@alexseipopov АПРУВ ПЛИЗ ВРЕМЯ ИДЕТ

2024-09-06 21:34 UTC, alexseipopov requested changes

2024-09-06 21:34 UTC, alexseipopov commented on internal/repository/db/repository.go
> +func (r *Repository) UpdateUserInvite(userInvite string) error {
этот метод по хорошему должен принимать initiator и invited - и по уникальной записи простовлять что для этого кейса было учтено приглашение. Сейчас этот метод меняет сразу пачкой статусы, нужно сделать чтобы один вызов - одно изменение

2024-09-07 10:12 UTC, alexseipopov requested changes

2024-09-07 10:12 UTC, alexseipopov commented on internal/repository/kafka/consumer/user_new_peer/contract.go
> +type Storage interface {
Вроде же он не был Storage. Их по хорошему называют в тему. и подписывают что это (сервис, репозиторий, модель итак далее). в этом случае это обращение к слою репозитория, а в репозитории к кому идем, к db. Следовательно тут лучше назвать dbRepo интерфейс

2024-09-07 10:12 UTC, alexseipopov commented on internal/repository/kafka/producer/notification_new_user/contract.go
> +type Storage interface {
тут так же

2024-09-07 10:12 UTC, alexseipopov commented on internal/repository/kafka/producer/notification_new_user/producer.go
> +	storage  Storage
тут, в силу того, что может быть (а может и даже будет) много служб - их принято называть абривиатурой с указанием в конце на то, что это , репозиторий, сервис и так далее(абривиатура маленькими буквами, указатель с большой. Тут стоит назвать переменную dbR . тип ее будет dbRepo

2024-09-07 10:12 UTC, alexseipopov commented on internal/repository/kafka/producer/notification_new_user/producer.go
> +	}{Email: email,
тут заметил, давай перенесем, чтобы было
{
    Email: email,
    UUID: value,
}

2024-09-07 12:23 UTC, vladimirfrolovv commented on cmd/workers/notification/main.go
> +	"github.com/s21platform/friends-service/internal/repository/kafka/producer/notification_new_user"
Нужен Alias к package

2024-09-07 12:23 UTC, alexseipopov commented on cmd/workers/notification/main.go
> +		log.Printf("db.New: %v", err)
давай тут сделаем log.Fatalf он сам выйдет. без exit(1)

2024-09-07 12:25 UTC, vladimirfrolovv commented on internal/repository/db/repository.go
> +	row, err := r.connection.Query("SELECT initiator FROM user_invite WHERE invited = $1", string(email))
Sql query нужен const

2024-09-07 12:27 UTC, alexseipopov commented on cmd/workers/notification/main.go
> +	"github.com/s21platform/friends-service/internal/repository/kafka/producer/notification_new_user"
например notificationnewuser

2024-09-07 12:27 UTC, alexseipopov commented on cmd/workers/notification/main.go
> +	"github.com/s21platform/friends-service/internal/repository/kafka/consumer/user_new_peer"
тут так же элиас

2024-09-07 12:31 UTC, vladimirfrolovv commented on internal/repository/db/repository.go
> +	_, err := r.connection.Exec("UPDATE user_invite SET is_closed=true WHERE initiator=$1 AND invited=$2",
Опять const

2024-09-07 15:57 UTC, alexseipopov approved these changes

2024-09-07 15:59 UTC, merged